= My Reading List

A hugely incomplete list of the books I've read lately.

== Reading

- Creative Selection: Inside Apple's Design Process During the Golden Age of Steve Jobs (Ken Kocienda)
- Mythos (Stephen Fry)

== Read

- BUILD: An Unorthodox Guide to Making Things Worth Making (Tony Fadell)
- The Soul of a New Machine (Tracy Kidder)
- Skunk Works: A Personal Memoir of My Years of Lockheed (Ben R. Rich, Leo Janos)
- Dealers of Lightning: Xerox PARC and the Dawn of the Computer Age (Michael Hiltzik)
- Category Theory in Context (Emily Riehl)
- Seven Sketches in Compositionality (Brendan Fong, David Spivak)
- The Book of Yokai (Michael Dylan Foster)
- The Hidden Game of Baseball: A Revolutionary Approach to Baseball and Its Statistics (David Reuther, John Thorn, and Pete Palmer)
- The Little MLer (Matthias Felleisen)
- The Art of Logic (Eugenia Cheng)
- Read Real Japanese Essays: Contemporary Writings by Popular Authors (Janet Ashby)
- Read Real Japanese Fiction: Short Stories by Contemporary Writers (Michael Emmerich)
- One Hundred Years of Solitude (Gabriel Garcia Marquez)
- Fundamentals of Software Architecture (Mark Richards, Neal Ford)
- Software Foundations
- Category Theory: A Gentle Introduction (Peter Smith)
- Type Theory and Functional Programming (Simon Thompson)
- The Unconsoled (Kazuo Ishiguro)
- How to Bake Pi (Eugenia Cheng)
- Breaking into Japanese Literature: Seven Modern Classics in Parallel Text (Giles Murray)
- The Book of General Ignorance (John Mitchinson, John Lloyd)
- Whistlestop (John Dickerson)
- Believer: My Forty Years in Politics (David Axelrod)
- Ametora: How Japan Saved American Style (W. David Marx)
- Don Quixote (Miguel de Cervantes, Edith Grossman)
- Surely You're Joking, Mr. Feynman! (Richard Feynman)
- Where Wizards Stay Up Late: The Origins of the Internet (Katie Hafner)
- The Idea Factory: Bell Labs and the Great Age of American Innovation (Jon Gertner)
- Masterminds of Programming: Conversations with the Creators of Major Programming Languages (Federico Biancuzzi)
- Land of Lisp (Conrad Barski)
- American Gods (Neil Gaiman)
- Coders at Work (Peter Seibel)
- 1Q84 (Murakami)
- Kafka on the Shore (Murakami)
- The Wind-Up Bird Chronicle (Murakami)
