#+Title: Johnny Megahan, Software Engineer - Tokyo, Japan
#+Author: Johnny Megahan
#+Email: megahanj@acm.org
#+Description: The home page of Johnny Megahan, a software engineer.
#+Options: html-style:nil html-scripts:nil html-postamble:nil toc:nil num:nil

* こんにちは！

Hello, I'm Johnny.

I like to focus on fitting functional patterns into domain
logic. Recently I've done that in Haskell, Javascript, and OCaml.

Here's a link to my [[file:bookshelf.org][reading list]], though it is perpetually out of
date.

Shibuya, Tokyo is my home, after having spent much of my time in San
Francisco, Wilmington, and Pittsburgh.

I am most happy in the back corner booth of a warm cafe.

After some time spent studying Japanese and Category Theory, I am
currently working at Coursebase (Tokyo) on educational tools.

Previous to that, I was:
- Senior Engineer on Uber's Core Web Platform team
- Senior Engineer on Apple's Music team (for iTunes Desktop, Apple TV
  Music, and IOS Music)
- Senior Engineer on Beats Music's Web team
- Software Engineer at MOG, PBS, and others.

You may find me on social media at the following sites:
- [[http://twitter.com/johnmegahan][twitter: @johnmegahan]]
- [[https://github.com/johnmegahan][github: @johnmegahan]]
- [[http://www.linkedin.com/in/johnmegahan/][linkedin: @johnmegahan]]

You may email me at [[mailto:megahanj@acm.org][megahanj@acm.org]]
