#+Title: Johnny Megahan, Software Engineer - Tokyo, Japan
#+Author: Johnny Megahan
#+Email: megahanj@acm.org
#+Description: The home page of Johnny Megahan, a software engineer.
#+Options: html-style:nil html-scripts:nil html-postamble:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/style.css" />

* どうも！
:PROPERTIES:
:CUSTOM_ID: about
:END:

I'm a former Yinzer, Delawarean, San Franciscan, and a current Tokyoite, happily
living on the edge of Shibuya with my wife and our pup.

I've been programming since I was 8, writing small trivia games in lisp and basic.
But I've spent the past 10 years working in small startups and international companies
with anywhere from 3 to 3k engineers.

I enjoy focusing on high-impact changes and I love rethinking systems. The great thing
is that means I'm never bored. I can be doing anything from domain planning, architecting
distributed systems, writing a low-level effect system, pairing with other engineers,
digging into database or runtime internals, or simply fixing a ui bug that has been
annoying a user for months.

I'm interested in funtional programming, domain driven design, event sourcing,
type systems, and how we can combine all of those things to create a great system.

I usually spend my free time reading, travelling, or painting watercolor.

Here's a link to my [[file:bookshelf.org][current reading list]]

** 仕事
:PROPERTIES:
:CUSTOM_ID: work
:END:

I am currently working at Coursebase, where I enjoy working all the way up and
down the stack building educational software.

Previous to that I was an engineer at:

Uber, where I worked on core frameworks and systems for web services
Apple, where I worked on planning and frameworks for Apple Music and AppleTv
Beats Music, where I worked on the system and architecture for the browser-based web player
PBS (wedu), where I worked on building low-cost, high performance web services

** 連絡
:PROPERTIES:
:CUSTOM_ID: contact
:END:

I am taking a break from social media but you may email me at [[mailto:megahanj@acm.org][megahanj@acm.org]]
