#+Title: Johnny Megahan, Software Engineer - Tokyo, Japan
#+Author: Johnny Megahan
#+Email: megahanj@acm.org
#+Description: The home page of Johnny Megahan, a software engineer.
#+Options: html-style:nil html-scripts:nil html-postamble:nil toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/style.css" />

* どうも！
:PROPERTIES:
:CUSTOM_ID: about
:END:

I'm a former Yinzer, San Franciscan, and a current Tokyoite, happily living on
the edge of Shibuya with my wife and our pup.

On the technical side of things, I'm interested in effect and type systems,
functional languages, domain design, software architecture, and systems design.
I enjoy a variety of hobbies and recently I've been spending much of my free
time painting watercolor.

Here's a link to my [[file:bookshelf.org][current reading list]]

** 仕事
:PROPERTIES:
:CUSTOM_ID: work
:END:

I am currently working at Coursebase (Tokyo) on educational software.

Previous to that I took some time off to study Japanese and Category Theory.
Before that I was a Senior Software Engineer at Uber, Apple, Beats Music, MOG,
and PBS.

** 連絡
:PROPERTIES:
:CUSTOM_ID: contact
:END:

I view social media mostly as read-only but you may email me at [[mailto:megahanj@acm.org][megahanj@acm.org]]
