#+Title: Johnny Megahan, Software Engineer - Tokyo, Japan
#+Author: Johnny Megahan
#+Email: megahanj@acm.org
#+Description: The home page of Johnny Megahan, a software engineer.
#+Options: html-style:nil html-scripts:nil html-postamble:nil toc:nil num:nil

Hello, I'm Johnny!

I'm happily living in the outskirts of Shibuya, Tokyo with my wife and
our pup. If you're in the area and interested in talking about
functional programming, software engineering, or Pittsburgh sports,
feel free to give me a shout. I'm especially happy to help
under-represented people new to the profession get their feet under
them and understand that none of us really know everything.

I am most happy in the back corner booth of a warm cafe, but that's
not really something 2020 had in the cards.

I've been writing software and designing systems for about 13 years
now and I think I'm starting to understand some things. The two
biggest ideas to impact how I design systems are Domain-Driven Design
and Functional Programming. Naturally, I like to focus on how to
combine them in ways that end up hopefully appearing fantastically
boring and obvious.

Here's a link to my [[file:bookshelf.org][reading list]], though it is perpetually out of
date.

I currently work at Coursebase on learning software, doing everything
from feature development to architecture/design to infrastructure.

Previous to that, I was:
- Senior Engineer on Uber's Core Web Platform team
- Senior Engineer on Apple's Music team (for iTunes Desktop, Apple TV
  Music, and IOS Music)
- Senior Engineer on Beats Music's Web team
- Software Engineer at MOG, PBS, and others.

If you'd like to get in touch with me you may email me at
[[mailto:megahanj@acm.org][megahanj@acm.org]].
